"""Roles de usuario

Revision ID: 15abf466c1b0
Revises: 
Create Date: 2018-09-15 04:32:09.756978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15abf466c1b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rol',
    sa.Column('id_rol', sa.BigInteger(), nullable=False),
    sa.Column('nombre_rol', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizad_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_index(op.f('ix_rol_actualizad_en'), 'rol', ['actualizad_en'], unique=False)
    op.create_index(op.f('ix_rol_creado_en'), 'rol', ['creado_en'], unique=False)
    op.create_index(op.f('ix_rol_nombre_rol'), 'rol', ['nombre_rol'], unique=True)
    op.create_table('rol_usuario',
    sa.Column('id_rol_user', sa.BigInteger(), nullable=False),
    sa.Column('fk_id_usuario', sa.BigInteger(), nullable=True),
    sa.Column('fk_id_rol', sa.BigInteger(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizad_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_id_rol'], ['rol.id_rol'], ),
    sa.ForeignKeyConstraint(['fk_id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_rol_user')
    )
    op.create_index(op.f('ix_rol_usuario_actualizad_en'), 'rol_usuario', ['actualizad_en'], unique=False)
    op.create_index(op.f('ix_rol_usuario_creado_en'), 'rol_usuario', ['creado_en'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rol_usuario_creado_en'), table_name='rol_usuario')
    op.drop_index(op.f('ix_rol_usuario_actualizad_en'), table_name='rol_usuario')
    op.drop_table('rol_usuario')
    op.drop_index(op.f('ix_rol_nombre_rol'), table_name='rol')
    op.drop_index(op.f('ix_rol_creado_en'), table_name='rol')
    op.drop_index(op.f('ix_rol_actualizad_en'), table_name='rol')
    op.drop_table('rol')
    # ### end Alembic commands ###
