"""cambio de numeros telefonicos a string

Revision ID: 34720a9ed3ac
Revises: 8bfcf508e406
Create Date: 2026-04-30 23:14:53.879465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34720a9ed3ac'
down_revision: Union[str, Sequence[str], None] = '8bfcf508e406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cliente', 'apellido',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cliente', 'numero',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('cliente', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('empleado', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('empleado', 'apellido',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('empleado', 'numero',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('empleado', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empleado', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('empleado', 'numero',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('empleado', 'apellido',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('empleado', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cliente', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cliente', 'numero',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('cliente', 'apellido',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cliente', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
