"""Base de datos 1.5

Revision ID: 4ae1a0ee7b2d
Revises: 
Create Date: 2026-05-29 11:56:15.464527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae1a0ee7b2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_index(op.f('ix_cliente_apellido'), 'cliente', ['apellido'], unique=False)
    op.create_index(op.f('ix_cliente_nombre'), 'cliente', ['nombre'], unique=False)
    op.create_table('cost_adm',
    sa.Column('id_costo_adm', sa.BigInteger(), nullable=False),
    sa.Column('tipo_costo', sa.String(), nullable=True),
    sa.Column('gasto_administrativo', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id_costo_adm')
    )
    op.create_index(op.f('ix_cost_adm_tipo_costo'), 'cost_adm', ['tipo_costo'], unique=False)
    op.create_table('cost_op',
    sa.Column('id_costo_oper', sa.BigInteger(), nullable=False),
    sa.Column('tipo_gasto_operativo', sa.String(), nullable=True),
    sa.Column('gasto_operativo', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id_costo_oper')
    )
    op.create_index(op.f('ix_cost_op_tipo_gasto_operativo'), 'cost_op', ['tipo_gasto_operativo'], unique=False)
    op.create_table('empleado',
    sa.Column('id_empleado', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_empleado')
    )
    op.create_index(op.f('ix_empleado_apellido'), 'empleado', ['apellido'], unique=False)
    op.create_index(op.f('ix_empleado_nombre'), 'empleado', ['nombre'], unique=False)
    op.create_table('materia_prima',
    sa.Column('id_materia', sa.BigInteger(), nullable=False),
    sa.Column('tipo_material', sa.String(), nullable=True),
    sa.Column('precio_mat', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_materia')
    )
    op.create_index(op.f('ix_materia_prima_tipo_material'), 'materia_prima', ['tipo_material'], unique=False)
    op.create_table('permiso',
    sa.Column('id_permiso', sa.BigInteger(), nullable=False),
    sa.Column('nombre_permiso', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizad_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_permiso')
    )
    op.create_index(op.f('ix_permiso_actualizad_en'), 'permiso', ['actualizad_en'], unique=False)
    op.create_index(op.f('ix_permiso_creado_en'), 'permiso', ['creado_en'], unique=False)
    op.create_index(op.f('ix_permiso_nombre_permiso'), 'permiso', ['nombre_permiso'], unique=True)
    op.create_table('producto',
    sa.Column('id_producto', sa.BigInteger(), nullable=False),
    sa.Column('nombre_p', sa.String(), nullable=True),
    sa.Column('tipo_p', sa.String(), nullable=True),
    sa.Column('precio_p', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_index(op.f('ix_producto_nombre_p'), 'producto', ['nombre_p'], unique=False)
    op.create_index(op.f('ix_producto_tipo_p'), 'producto', ['tipo_p'], unique=False)
    op.create_table('rol',
    sa.Column('id_rol', sa.BigInteger(), nullable=False),
    sa.Column('nombre_rol', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizad_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_index(op.f('ix_rol_actualizad_en'), 'rol', ['actualizad_en'], unique=False)
    op.create_index(op.f('ix_rol_creado_en'), 'rol', ['creado_en'], unique=False)
    op.create_index(op.f('ix_rol_nombre_rol'), 'rol', ['nombre_rol'], unique=True)
    op.create_table('detalle_pro',
    sa.Column('id_det_pro', sa.BigInteger(), nullable=False),
    sa.Column('tallas', sa.String(), nullable=True),
    sa.Column('cantidad_talla', sa.Integer(), nullable=True),
    sa.Column('fk_producto', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['fk_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_det_pro')
    )
    op.create_index(op.f('ix_detalle_pro_tallas'), 'detalle_pro', ['tallas'], unique=False)
    op.create_table('pedido',
    sa.Column('id_pedido', sa.BigInteger(), nullable=False),
    sa.Column('fk_cliente', sa.BigInteger(), nullable=True),
    sa.Column('pe_desc', sa.String(), nullable=True),
    sa.Column('fk_producto', sa.BigInteger(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fk_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['fk_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_table('permiso_rol',
    sa.Column('id_permiso_rol', sa.BigInteger(), nullable=False),
    sa.Column('fk_id_rol', sa.BigInteger(), nullable=True),
    sa.Column('fk_id_permiso', sa.BigInteger(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizad_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_id_permiso'], ['permiso.id_permiso'], ),
    sa.ForeignKeyConstraint(['fk_id_rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_permiso_rol')
    )
    op.create_index(op.f('ix_permiso_rol_actualizad_en'), 'permiso_rol', ['actualizad_en'], unique=False)
    op.create_index(op.f('ix_permiso_rol_creado_en'), 'permiso_rol', ['creado_en'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('empleado_fk', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_fk'], ['empleado.id_empleado'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empleado_fk')
    )
    op.create_index(op.f('ix_users_hashed_password'), 'users', ['hashed_password'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.create_table('actividad',
    sa.Column('id_actividad', sa.BigInteger(), nullable=False),
    sa.Column('fk_empleado', sa.BigInteger(), nullable=True),
    sa.Column('fk_pedido', sa.BigInteger(), nullable=True),
    sa.Column('descripcion_tarea', sa.String(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_final', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fk_empleado'], ['empleado.id_empleado'], ),
    sa.ForeignKeyConstraint(['fk_pedido'], ['pedido.id_pedido'], ),
    sa.PrimaryKeyConstraint('id_actividad')
    )
    op.create_index(op.f('ix_actividad_descripcion_tarea'), 'actividad', ['descripcion_tarea'], unique=False)
    op.create_index(op.f('ix_actividad_fecha_final'), 'actividad', ['fecha_final'], unique=False)
    op.create_index(op.f('ix_actividad_fecha_inicio'), 'actividad', ['fecha_inicio'], unique=False)
    op.create_table('detalles_pedido',
    sa.Column('id_detalle_pedido', sa.BigInteger(), nullable=False),
    sa.Column('fk_pedido', sa.BigInteger(), nullable=True),
    sa.Column('tallas', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fk_pedido'], ['pedido.id_pedido'], ),
    sa.PrimaryKeyConstraint('id_detalle_pedido')
    )
    op.create_table('rol_usuario',
    sa.Column('id_rol_user', sa.BigInteger(), nullable=False),
    sa.Column('fk_id_usuario', sa.BigInteger(), nullable=True),
    sa.Column('fk_id_rol', sa.BigInteger(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizad_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_id_rol'], ['rol.id_rol'], ),
    sa.ForeignKeyConstraint(['fk_id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_rol_user')
    )
    op.create_index(op.f('ix_rol_usuario_actualizad_en'), 'rol_usuario', ['actualizad_en'], unique=False)
    op.create_index(op.f('ix_rol_usuario_creado_en'), 'rol_usuario', ['creado_en'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rol_usuario_creado_en'), table_name='rol_usuario')
    op.drop_index(op.f('ix_rol_usuario_actualizad_en'), table_name='rol_usuario')
    op.drop_table('rol_usuario')
    op.drop_table('detalles_pedido')
    op.drop_index(op.f('ix_actividad_fecha_inicio'), table_name='actividad')
    op.drop_index(op.f('ix_actividad_fecha_final'), table_name='actividad')
    op.drop_index(op.f('ix_actividad_descripcion_tarea'), table_name='actividad')
    op.drop_table('actividad')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_hashed_password'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_permiso_rol_creado_en'), table_name='permiso_rol')
    op.drop_index(op.f('ix_permiso_rol_actualizad_en'), table_name='permiso_rol')
    op.drop_table('permiso_rol')
    op.drop_table('pedido')
    op.drop_index(op.f('ix_detalle_pro_tallas'), table_name='detalle_pro')
    op.drop_table('detalle_pro')
    op.drop_index(op.f('ix_rol_nombre_rol'), table_name='rol')
    op.drop_index(op.f('ix_rol_creado_en'), table_name='rol')
    op.drop_index(op.f('ix_rol_actualizad_en'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_producto_tipo_p'), table_name='producto')
    op.drop_index(op.f('ix_producto_nombre_p'), table_name='producto')
    op.drop_table('producto')
    op.drop_index(op.f('ix_permiso_nombre_permiso'), table_name='permiso')
    op.drop_index(op.f('ix_permiso_creado_en'), table_name='permiso')
    op.drop_index(op.f('ix_permiso_actualizad_en'), table_name='permiso')
    op.drop_table('permiso')
    op.drop_index(op.f('ix_materia_prima_tipo_material'), table_name='materia_prima')
    op.drop_table('materia_prima')
    op.drop_index(op.f('ix_empleado_nombre'), table_name='empleado')
    op.drop_index(op.f('ix_empleado_apellido'), table_name='empleado')
    op.drop_table('empleado')
    op.drop_index(op.f('ix_cost_op_tipo_gasto_operativo'), table_name='cost_op')
    op.drop_table('cost_op')
    op.drop_index(op.f('ix_cost_adm_tipo_costo'), table_name='cost_adm')
    op.drop_table('cost_adm')
    op.drop_index(op.f('ix_cliente_nombre'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_apellido'), table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
