"""añadido fechas en coste op y adm, falla critica de eliminacion logica solucionada

Revision ID: 534757c8257d
Revises: 484fc948affc
Create Date: 2026-08-31 12:18:37.080454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '534757c8257d'
down_revision: Union[str, Sequence[str], None] = '484fc948affc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_changed_by'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_table_name'), table_name='audit_log')
    op.drop_table('audit_log')
    op.alter_column('actividad', 'fecha_inicio',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('actividad', 'fecha_final',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.add_column('cost_adm', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('cost_op', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('detalle_pro', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('materia_prima', sa.Column('fecha', sa.Date(), nullable=True))
    op.create_index(op.f('ix_materia_prima_fecha'), 'materia_prima', ['fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materia_prima_fecha'), table_name='materia_prima')
    op.drop_column('materia_prima', 'fecha')
    op.drop_column('detalle_pro', 'is_active')
    op.drop_column('cost_op', 'is_active')
    op.drop_column('cost_adm', 'is_active')
    op.alter_column('actividad', 'fecha_final',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('actividad', 'fecha_inicio',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_table('audit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('changed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_pkey'))
    )
    op.create_index(op.f('ix_audit_log_table_name'), 'audit_log', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_log_changed_by'), 'audit_log', ['changed_by'], unique=False)
    # ### end Alembic commands ###
