"""Reacomodo y ajuste de tablas clave

Revision ID: 6f7b53166920
Revises: 
Create Date: 2026-04-27 19:30:22.584711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7b53166920'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_index(op.f('ix_cliente_apellido'), 'cliente', ['apellido'], unique=False)
    op.create_index(op.f('ix_cliente_nombre'), 'cliente', ['nombre'], unique=False)
    op.create_table('cost_adm',
    sa.Column('id_materia', sa.BigInteger(), nullable=False),
    sa.Column('impuestos', sa.String(), nullable=True),
    sa.Column('alquiler', sa.String(), nullable=True),
    sa.Column('gastos_adm', sa.String(), nullable=True),
    sa.Column('publicidad', sa.String(), nullable=True),
    sa.Column('gasolina', sa.String(), nullable=True),
    sa.Column('moto_taxi', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_materia')
    )
    op.create_index(op.f('ix_cost_adm_alquiler'), 'cost_adm', ['alquiler'], unique=False)
    op.create_index(op.f('ix_cost_adm_gasolina'), 'cost_adm', ['gasolina'], unique=False)
    op.create_index(op.f('ix_cost_adm_gastos_adm'), 'cost_adm', ['gastos_adm'], unique=False)
    op.create_index(op.f('ix_cost_adm_impuestos'), 'cost_adm', ['impuestos'], unique=False)
    op.create_index(op.f('ix_cost_adm_moto_taxi'), 'cost_adm', ['moto_taxi'], unique=False)
    op.create_index(op.f('ix_cost_adm_publicidad'), 'cost_adm', ['publicidad'], unique=False)
    op.create_table('cost_op',
    sa.Column('id_materia', sa.BigInteger(), nullable=False),
    sa.Column('corte', sa.String(), nullable=True),
    sa.Column('confeccion', sa.String(), nullable=True),
    sa.Column('ojal', sa.String(), nullable=True),
    sa.Column('bordado', sa.String(), nullable=True),
    sa.Column('sublimado', sa.String(), nullable=True),
    sa.Column('plancha', sa.String(), nullable=True),
    sa.Column('plancha_ter', sa.String(), nullable=True),
    sa.Column('diseño', sa.String(), nullable=True),
    sa.Column('montaje', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_materia')
    )
    op.create_index(op.f('ix_cost_op_bordado'), 'cost_op', ['bordado'], unique=False)
    op.create_index(op.f('ix_cost_op_confeccion'), 'cost_op', ['confeccion'], unique=False)
    op.create_index(op.f('ix_cost_op_corte'), 'cost_op', ['corte'], unique=False)
    op.create_index(op.f('ix_cost_op_diseño'), 'cost_op', ['diseño'], unique=False)
    op.create_index(op.f('ix_cost_op_montaje'), 'cost_op', ['montaje'], unique=False)
    op.create_index(op.f('ix_cost_op_ojal'), 'cost_op', ['ojal'], unique=False)
    op.create_index(op.f('ix_cost_op_plancha'), 'cost_op', ['plancha'], unique=False)
    op.create_index(op.f('ix_cost_op_plancha_ter'), 'cost_op', ['plancha_ter'], unique=False)
    op.create_index(op.f('ix_cost_op_sublimado'), 'cost_op', ['sublimado'], unique=False)
    op.create_table('empleado',
    sa.Column('id_empleado', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_empleado')
    )
    op.create_index(op.f('ix_empleado_apellido'), 'empleado', ['apellido'], unique=False)
    op.create_index(op.f('ix_empleado_nombre'), 'empleado', ['nombre'], unique=False)
    op.create_table('materia_prima',
    sa.Column('id_materia', sa.BigInteger(), nullable=False),
    sa.Column('tipo_material', sa.String(), nullable=True),
    sa.Column('precio_mat', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_materia')
    )
    op.create_index(op.f('ix_materia_prima_tipo_material'), 'materia_prima', ['tipo_material'], unique=False)
    op.create_table('producto',
    sa.Column('id_producto', sa.BigInteger(), nullable=False),
    sa.Column('nombre_p', sa.String(), nullable=True),
    sa.Column('tipo_p', sa.String(), nullable=True),
    sa.Column('detalle_p', sa.String(), nullable=True),
    sa.Column('precio_p', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_index(op.f('ix_producto_nombre_p'), 'producto', ['nombre_p'], unique=False)
    op.create_index(op.f('ix_producto_tipo_p'), 'producto', ['tipo_p'], unique=False)
    op.create_table('detalle_pro',
    sa.Column('id_det_pro', sa.BigInteger(), nullable=False),
    sa.Column('tallas', sa.String(), nullable=True),
    sa.Column('cantidad_talla', sa.Integer(), nullable=True),
    sa.Column('fk_producto', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['fk_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_det_pro')
    )
    op.create_index(op.f('ix_detalle_pro_tallas'), 'detalle_pro', ['tallas'], unique=False)
    op.create_table('pedido',
    sa.Column('id_pedido', sa.BigInteger(), nullable=False),
    sa.Column('fk_cliente', sa.BigInteger(), nullable=True),
    sa.Column('pe_desc', sa.String(), nullable=True),
    sa.Column('fk_producto', sa.BigInteger(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fk_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['fk_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('contrasena', sa.String(), nullable=True),
    sa.Column('empleado_fk', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_fk'], ['empleado.id_empleado'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_contrasena'), 'users', ['contrasena'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_contrasena'), table_name='users')
    op.drop_table('users')
    op.drop_table('pedido')
    op.drop_index(op.f('ix_detalle_pro_tallas'), table_name='detalle_pro')
    op.drop_table('detalle_pro')
    op.drop_index(op.f('ix_producto_tipo_p'), table_name='producto')
    op.drop_index(op.f('ix_producto_nombre_p'), table_name='producto')
    op.drop_table('producto')
    op.drop_index(op.f('ix_materia_prima_tipo_material'), table_name='materia_prima')
    op.drop_table('materia_prima')
    op.drop_index(op.f('ix_empleado_nombre'), table_name='empleado')
    op.drop_index(op.f('ix_empleado_apellido'), table_name='empleado')
    op.drop_table('empleado')
    op.drop_index(op.f('ix_cost_op_sublimado'), table_name='cost_op')
    op.drop_index(op.f('ix_cost_op_plancha_ter'), table_name='cost_op')
    op.drop_index(op.f('ix_cost_op_plancha'), table_name='cost_op')
    op.drop_index(op.f('ix_cost_op_ojal'), table_name='cost_op')
    op.drop_index(op.f('ix_cost_op_montaje'), table_name='cost_op')
    op.drop_index(op.f('ix_cost_op_diseño'), table_name='cost_op')
    op.drop_index(op.f('ix_cost_op_corte'), table_name='cost_op')
    op.drop_index(op.f('ix_cost_op_confeccion'), table_name='cost_op')
    op.drop_index(op.f('ix_cost_op_bordado'), table_name='cost_op')
    op.drop_table('cost_op')
    op.drop_index(op.f('ix_cost_adm_publicidad'), table_name='cost_adm')
    op.drop_index(op.f('ix_cost_adm_moto_taxi'), table_name='cost_adm')
    op.drop_index(op.f('ix_cost_adm_impuestos'), table_name='cost_adm')
    op.drop_index(op.f('ix_cost_adm_gastos_adm'), table_name='cost_adm')
    op.drop_index(op.f('ix_cost_adm_gasolina'), table_name='cost_adm')
    op.drop_index(op.f('ix_cost_adm_alquiler'), table_name='cost_adm')
    op.drop_table('cost_adm')
    op.drop_index(op.f('ix_cliente_nombre'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_apellido'), table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
