"""Actualizacion de productos y detalle productos

Revision ID: 89aedcab6251
Revises: 4ae1a0ee7b2d
Create Date: 2026-07-26 14:27:29.663787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89aedcab6251'
down_revision: Union[str, Sequence[str], None] = '4ae1a0ee7b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalle_pro', sa.Column('cantidad', sa.Integer(), nullable=True))
    op.drop_column('detalle_pro', 'cantidad_talla')
    op.drop_column('producto', 'cantidad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('detalle_pro', sa.Column('cantidad_talla', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('detalle_pro', 'cantidad')
    # ### end Alembic commands ###
