"""cambios

Revision ID: 8bfcf508e406
Revises: 7b786828c20b
Create Date: 2026-04-30 22:34:24.565222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bfcf508e406'
down_revision: Union[str, Sequence[str], None] = '7b786828c20b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_index(op.f('ix_users_contrasena'), table_name='users')
    op.create_index(op.f('ix_users_hashed_password'), 'users', ['hashed_password'], unique=True)
    op.drop_column('users', 'contrasena')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contrasena', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_hashed_password'), table_name='users')
    op.create_index(op.f('ix_users_contrasena'), 'users', ['contrasena'], unique=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
