"""se agrego la tabla ventas

Revision ID: 8d54977cb87e
Revises: a61c551a1109
Create Date: 2026-09-04 12:52:44.737236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d54977cb87e'
down_revision: Union[str, Sequence[str], None] = 'a61c551a1109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ventas',
    sa.Column('id_ventas', sa.BigInteger(), nullable=False),
    sa.Column('fk_producto', sa.BigInteger(), nullable=True),
    sa.Column('precio_p', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fk_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_ventas')
    )
    op.create_index(op.f('ix_ventas_fecha'), 'ventas', ['fecha'], unique=False)
    op.add_column('pedido', sa.Column('fecha', sa.Date(), nullable=True))
    op.create_index(op.f('ix_pedido_fecha'), 'pedido', ['fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_fecha'), table_name='pedido')
    op.drop_column('pedido', 'fecha')
    op.create_table('audit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('changed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_pkey'))
    )
    op.create_index(op.f('ix_audit_log_table_name'), 'audit_log', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_log_changed_by'), 'audit_log', ['changed_by'], unique=False)
    op.drop_index(op.f('ix_ventas_fecha'), table_name='ventas')
    op.drop_table('ventas')
    # ### end Alembic commands ###
