"""cambios en tabla usuario

Revision ID: a17599484fc7
Revises: f2dcc9c09546
Create Date: 2026-05-03 12:56:31.481919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a17599484fc7'
down_revision: Union[str, Sequence[str], None] = 'f2dcc9c09546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'empleado_fk',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['empleado_fk'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'empleado_fk',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
