"""actualizacion de tablas de pedidos

Revision ID: aad02d44e6d1
Revises: cf59080aa638
Create Date: 2026-07-26 18:33:23.144337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad02d44e6d1'
down_revision: Union[str, Sequence[str], None] = 'cf59080aa638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalles_pedido', sa.Column('pe_desc', sa.String(), nullable=True))
    op.drop_column('pedido', 'cantidad')
    op.drop_column('pedido', 'pe_desc')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('pe_desc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pedido', sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('detalles_pedido', 'pe_desc')
    # ### end Alembic commands ###
