"""Tabla empleados añadida y relacionada a la tabla usuarios

Revision ID: b055296330b2
Revises: fcf130ea08ba
Create Date: 2026-04-22 19:40:13.298421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b055296330b2'
down_revision: Union[str, Sequence[str], None] = 'fcf130ea08ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleado',
    sa.Column('id_empleado', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_empleado')
    )
    op.create_index(op.f('ix_empleado_apellido'), 'empleado', ['apellido'], unique=False)
    op.create_index(op.f('ix_empleado_email'), 'empleado', ['email'], unique=False)
    op.create_index(op.f('ix_empleado_id_empleado'), 'empleado', ['id_empleado'], unique=False)
    op.create_index(op.f('ix_empleado_nombre'), 'empleado', ['nombre'], unique=False)
    op.create_index(op.f('ix_empleado_numero'), 'empleado', ['numero'], unique=False)
    op.drop_index(op.f('ix_post_apellido'), table_name='post')
    op.drop_index(op.f('ix_post_contrasena'), table_name='post')
    op.drop_index(op.f('ix_post_id'), table_name='post')
    op.drop_index(op.f('ix_post_nombre'), table_name='post')
    op.drop_table('post')
    op.add_column('users', sa.Column('empleado_fk', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'empleado', ['empleado_fk'], ['id_empleado'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'empleado_fk')
    op.create_table('post',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('apellido', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contrasena', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('post_pkey'))
    )
    op.create_index(op.f('ix_post_nombre'), 'post', ['nombre'], unique=False)
    op.create_index(op.f('ix_post_id'), 'post', ['id'], unique=False)
    op.create_index(op.f('ix_post_contrasena'), 'post', ['contrasena'], unique=False)
    op.create_index(op.f('ix_post_apellido'), 'post', ['apellido'], unique=False)
    op.drop_index(op.f('ix_empleado_numero'), table_name='empleado')
    op.drop_index(op.f('ix_empleado_nombre'), table_name='empleado')
    op.drop_index(op.f('ix_empleado_id_empleado'), table_name='empleado')
    op.drop_index(op.f('ix_empleado_email'), table_name='empleado')
    op.drop_index(op.f('ix_empleado_apellido'), table_name='empleado')
    op.drop_table('empleado')
    # ### end Alembic commands ###
