"""Tabla actividades actualizacion

Revision ID: cb2ddd9ba428
Revises: f7aaf3646761
Create Date: 2018-09-15 05:17:02.823055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2ddd9ba428'
down_revision: Union[str, Sequence[str], None] = 'f7aaf3646761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividad', sa.Column('fk_pedido', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'actividad', 'pedido', ['fk_pedido'], ['id_pedido'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actividad', type_='foreignkey')
    op.drop_column('actividad', 'fk_pedido')
    # ### end Alembic commands ###
