"""Actualizacion de costo operativo

Revision ID: cf59080aa638
Revises: 89aedcab6251
Create Date: 2026-07-26 14:50:56.737299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf59080aa638'
down_revision: Union[str, Sequence[str], None] = '89aedcab6251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_adm', sa.Column('fecha', sa.Date(), nullable=True))
    op.create_index(op.f('ix_cost_adm_fecha'), 'cost_adm', ['fecha'], unique=False)
    op.add_column('cost_op', sa.Column('fecha', sa.Date(), nullable=True))
    op.create_index(op.f('ix_cost_op_fecha'), 'cost_op', ['fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cost_op_fecha'), table_name='cost_op')
    op.drop_column('cost_op', 'fecha')
    op.drop_index(op.f('ix_cost_adm_fecha'), table_name='cost_adm')
    op.drop_column('cost_adm', 'fecha')
    # ### end Alembic commands ###
