"""Actualizacion de tablas de gastos

Revision ID: d40b43899c0c
Revises: cb2ddd9ba428
Create Date: 2026-04-30 17:38:27.405399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40b43899c0c'
down_revision: Union[str, Sequence[str], None] = 'cb2ddd9ba428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_adm', sa.Column('id_costo_adm', sa.BigInteger(), nullable=False))
    op.add_column('cost_adm', sa.Column('tipo_costo', sa.String(), nullable=True))
    op.add_column('cost_adm', sa.Column('gasto_administrativo', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_index(op.f('ix_cost_adm_alquiler'), table_name='cost_adm')
    op.drop_index(op.f('ix_cost_adm_gasolina'), table_name='cost_adm')
    op.drop_index(op.f('ix_cost_adm_gastos_adm'), table_name='cost_adm')
    op.drop_index(op.f('ix_cost_adm_impuestos'), table_name='cost_adm')
    op.drop_index(op.f('ix_cost_adm_moto_taxi'), table_name='cost_adm')
    op.drop_index(op.f('ix_cost_adm_publicidad'), table_name='cost_adm')
    op.create_index(op.f('ix_cost_adm_tipo_costo'), 'cost_adm', ['tipo_costo'], unique=False)
    op.drop_column('cost_adm', 'publicidad')
    op.drop_column('cost_adm', 'gastos_adm')
    op.drop_column('cost_adm', 'id_materia')
    op.drop_column('cost_adm', 'alquiler')
    op.drop_column('cost_adm', 'impuestos')
    op.drop_column('cost_adm', 'moto_taxi')
    op.drop_column('cost_adm', 'gasolina')
    op.add_column('cost_op', sa.Column('id_costo_oper', sa.BigInteger(), nullable=False))
    op.add_column('cost_op', sa.Column('tipo_gasto_operativo', sa.String(), nullable=True))
    op.add_column('cost_op', sa.Column('gasto_operativo', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_index(op.f('ix_cost_op_bordado'), table_name='cost_op')
    op.drop_index(op.f('ix_cost_op_confeccion'), table_name='cost_op')
    op.drop_index(op.f('ix_cost_op_corte'), table_name='cost_op')
    op.drop_index(op.f('ix_cost_op_diseño'), table_name='cost_op')
    op.drop_index(op.f('ix_cost_op_montaje'), table_name='cost_op')
    op.drop_index(op.f('ix_cost_op_ojal'), table_name='cost_op')
    op.drop_index(op.f('ix_cost_op_plancha'), table_name='cost_op')
    op.drop_index(op.f('ix_cost_op_plancha_ter'), table_name='cost_op')
    op.drop_index(op.f('ix_cost_op_sublimado'), table_name='cost_op')
    op.create_index(op.f('ix_cost_op_tipo_gasto_operativo'), 'cost_op', ['tipo_gasto_operativo'], unique=False)
    op.drop_column('cost_op', 'diseño')
    op.drop_column('cost_op', 'sublimado')
    op.drop_column('cost_op', 'id_materia')
    op.drop_column('cost_op', 'corte')
    op.drop_column('cost_op', 'bordado')
    op.drop_column('cost_op', 'plancha')
    op.drop_column('cost_op', 'montaje')
    op.drop_column('cost_op', 'ojal')
    op.drop_column('cost_op', 'plancha_ter')
    op.drop_column('cost_op', 'confeccion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_op', sa.Column('confeccion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cost_op', sa.Column('plancha_ter', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cost_op', sa.Column('ojal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cost_op', sa.Column('montaje', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cost_op', sa.Column('plancha', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cost_op', sa.Column('bordado', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cost_op', sa.Column('corte', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cost_op', sa.Column('id_materia', sa.BIGINT(), autoincrement=True, nullable=False))
    op.add_column('cost_op', sa.Column('sublimado', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cost_op', sa.Column('diseño', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_cost_op_tipo_gasto_operativo'), table_name='cost_op')
    op.create_index(op.f('ix_cost_op_sublimado'), 'cost_op', ['sublimado'], unique=False)
    op.create_index(op.f('ix_cost_op_plancha_ter'), 'cost_op', ['plancha_ter'], unique=False)
    op.create_index(op.f('ix_cost_op_plancha'), 'cost_op', ['plancha'], unique=False)
    op.create_index(op.f('ix_cost_op_ojal'), 'cost_op', ['ojal'], unique=False)
    op.create_index(op.f('ix_cost_op_montaje'), 'cost_op', ['montaje'], unique=False)
    op.create_index(op.f('ix_cost_op_diseño'), 'cost_op', ['diseño'], unique=False)
    op.create_index(op.f('ix_cost_op_corte'), 'cost_op', ['corte'], unique=False)
    op.create_index(op.f('ix_cost_op_confeccion'), 'cost_op', ['confeccion'], unique=False)
    op.create_index(op.f('ix_cost_op_bordado'), 'cost_op', ['bordado'], unique=False)
    op.drop_column('cost_op', 'gasto_operativo')
    op.drop_column('cost_op', 'tipo_gasto_operativo')
    op.drop_column('cost_op', 'id_costo_oper')
    op.add_column('cost_adm', sa.Column('gasolina', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cost_adm', sa.Column('moto_taxi', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cost_adm', sa.Column('impuestos', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cost_adm', sa.Column('alquiler', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cost_adm', sa.Column('id_materia', sa.BIGINT(), autoincrement=True, nullable=False))
    op.add_column('cost_adm', sa.Column('gastos_adm', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cost_adm', sa.Column('publicidad', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_cost_adm_tipo_costo'), table_name='cost_adm')
    op.create_index(op.f('ix_cost_adm_publicidad'), 'cost_adm', ['publicidad'], unique=False)
    op.create_index(op.f('ix_cost_adm_moto_taxi'), 'cost_adm', ['moto_taxi'], unique=False)
    op.create_index(op.f('ix_cost_adm_impuestos'), 'cost_adm', ['impuestos'], unique=False)
    op.create_index(op.f('ix_cost_adm_gastos_adm'), 'cost_adm', ['gastos_adm'], unique=False)
    op.create_index(op.f('ix_cost_adm_gasolina'), 'cost_adm', ['gasolina'], unique=False)
    op.create_index(op.f('ix_cost_adm_alquiler'), 'cost_adm', ['alquiler'], unique=False)
    op.drop_column('cost_adm', 'gasto_administrativo')
    op.drop_column('cost_adm', 'tipo_costo')
    op.drop_column('cost_adm', 'id_costo_adm')
    # ### end Alembic commands ###
