"""tablas para sistema de roles

Revision ID: f2dcc9c09546
Revises: 34720a9ed3ac
Create Date: 2026-04-30 23:27:31.240373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2dcc9c09546'
down_revision: Union[str, Sequence[str], None] = '34720a9ed3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permiso',
    sa.Column('id_permiso', sa.BigInteger(), nullable=False),
    sa.Column('nombre_permiso', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizad_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_permiso')
    )
    op.create_index(op.f('ix_permiso_actualizad_en'), 'permiso', ['actualizad_en'], unique=False)
    op.create_index(op.f('ix_permiso_creado_en'), 'permiso', ['creado_en'], unique=False)
    op.create_index(op.f('ix_permiso_nombre_permiso'), 'permiso', ['nombre_permiso'], unique=True)
    op.create_table('permiso_rol',
    sa.Column('id_permiso_rol', sa.BigInteger(), nullable=False),
    sa.Column('fk_id_rol', sa.BigInteger(), nullable=True),
    sa.Column('fk_id_permiso', sa.BigInteger(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizad_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_id_permiso'], ['permiso.id_permiso'], ),
    sa.ForeignKeyConstraint(['fk_id_rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_permiso_rol')
    )
    op.create_index(op.f('ix_permiso_rol_actualizad_en'), 'permiso_rol', ['actualizad_en'], unique=False)
    op.create_index(op.f('ix_permiso_rol_creado_en'), 'permiso_rol', ['creado_en'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permiso_rol_creado_en'), table_name='permiso_rol')
    op.drop_index(op.f('ix_permiso_rol_actualizad_en'), table_name='permiso_rol')
    op.drop_table('permiso_rol')
    op.drop_index(op.f('ix_permiso_nombre_permiso'), table_name='permiso')
    op.drop_index(op.f('ix_permiso_creado_en'), table_name='permiso')
    op.drop_index(op.f('ix_permiso_actualizad_en'), table_name='permiso')
    op.drop_table('permiso')
    # ### end Alembic commands ###
