"""Tabla actividades y tablas de detalles

Revision ID: f7aaf3646761
Revises: 15abf466c1b0
Create Date: 2018-09-15 05:06:53.195583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7aaf3646761'
down_revision: Union[str, Sequence[str], None] = '15abf466c1b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividad',
    sa.Column('id_actividad', sa.BigInteger(), nullable=False),
    sa.Column('fk_empleado', sa.BigInteger(), nullable=True),
    sa.Column('descripcion_tarea', sa.String(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_final', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fk_empleado'], ['empleado.id_empleado'], ),
    sa.PrimaryKeyConstraint('id_actividad')
    )
    op.create_index(op.f('ix_actividad_descripcion_tarea'), 'actividad', ['descripcion_tarea'], unique=False)
    op.create_index(op.f('ix_actividad_fecha_final'), 'actividad', ['fecha_final'], unique=False)
    op.create_index(op.f('ix_actividad_fecha_inicio'), 'actividad', ['fecha_inicio'], unique=False)
    op.create_table('detalles_pedido',
    sa.Column('id_detalle_pedido', sa.BigInteger(), nullable=False),
    sa.Column('fk_pedido', sa.BigInteger(), nullable=True),
    sa.Column('tallas', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fk_pedido'], ['pedido.id_pedido'], ),
    sa.PrimaryKeyConstraint('id_detalle_pedido')
    )
    op.add_column('producto', sa.Column('cantidad', sa.Integer(), nullable=True))
    op.drop_column('producto', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('producto', 'cantidad')
    op.drop_table('detalles_pedido')
    op.drop_index(op.f('ix_actividad_fecha_inicio'), table_name='actividad')
    op.drop_index(op.f('ix_actividad_fecha_final'), table_name='actividad')
    op.drop_index(op.f('ix_actividad_descripcion_tarea'), table_name='actividad')
    op.drop_table('actividad')
    # ### end Alembic commands ###
